2023-08-23 15:58:46 - INFO - [base_logger.py : 34] :: Initialized logger for the service [registration] :: [SUCCESS]
2023-08-23 15:58:46 - INFO - [create_app.py : 42] :: Received Service [registration]
2023-08-23 15:58:46 - INFO - [create_app.py : 44] :: Flask of Application Instance created for service [registration] ,  App Name :: [<Flask 'registration'>] ==> SUCCESS
2023-08-23 15:58:46 - INFO - [create_app.py : 53] :: Created Blueprint :: <Blueprint 'registration_bp'> for the Application service ::registration
2023-08-23 15:58:46 - INFO - [create_app.py : 70] :: Added Blueprints :: /static/<path:filename>
2023-08-23 15:58:46 - INFO - [create_app.py : 80] :: Creating DB-Engine using DatabaseURI for Service :: [registration]
2023-08-23 15:58:46 - INFO - [create_app.py : 74] :: Preparing DatabaseURI for Service :: [registration]
2023-08-23 15:58:46 - INFO - [create_app.py : 76] :: Prepared DatabaseURI for Service :: [registration] - mysql+pymysql://root:Ishi#06041995@127.0.0.1:3304/REGISTRATIONS
2023-08-23 15:58:46 - INFO - [create_app.py : 82] :: Created DB-Engine using DatabaseURIfor Service :: [Engine(mysql+pymysql://root:***@127.0.0.1:3304/REGISTRATIONS)]
2023-08-23 15:58:46 - INFO - [create_app.py : 111] :: Current Connection status set to :: False for the service :: registration
2023-08-23 15:58:46 - INFO - [create_app.py : 112] :: Trying to establish the connection to the database :: [IN-PROGRESS]
2023-08-23 15:58:46 - INFO - [create_app.py : 116] :: Established the connection to the database :: [SUCCESS]
2023-08-23 15:58:46 - INFO - [create_app.py : 118] :: Current Connection status set to :: True for the service :: registration
2023-08-23 15:58:46 - INFO - [create_app.py : 120] :: Closing the Current Connection as the connection was established for the service :: registration
2023-08-23 15:58:46 - INFO - [create_app.py : 153] :: Database already exists :: REGISTRATIONS
2023-08-23 15:58:46 - INFO - [create_app.py : 129] :: Trying to create the tables if not present in the database...
2023-08-23 15:58:46 - INFO - [create_app.py : 131] :: Going to create the tables ...
2023-08-23 15:58:46 - INFO - [create_app.py : 134] :: Created the tables ...
2023-08-23 15:58:46 - INFO - [create_app.py : 87] :: Binding SQLALCHEMY using DatabaseURI:: [mysql+pymysql://root:Ishi#06041995@127.0.0.1:3304/REGISTRATIONS] to Application Instance for Service :: [registration]
2023-08-23 15:58:46 - INFO - [create_app.py : 89] :: Binded SQLALCHEMY :: [<SQLAlchemy>] to Application Instance for Service :: [registration]
2023-08-23 15:58:46 - INFO - [create_app.py : 93] :: Initialized Pool for Service ==>[registration] :: [SUCCESS]
2023-08-23 15:58:46 - INFO - [create_app.py : 162] :: #---------------------------------[ POOL - INFO ]----------------------------------------#
2023-08-23 15:58:46 - INFO - [create_app.py : 163] :: Displaying Pool_Info for Service ==>[registration] 
2023-08-23 15:58:46 - INFO - [create_app.py : 164] :: Current Pool Info :: <sqlalchemy.pool.impl.QueuePool object at 0x1056b9850> - ID: 4385904720
2023-08-23 15:58:46 - INFO - [create_app.py : 165] :: Current Pool Size ::  100
2023-08-23 15:58:46 - INFO - [create_app.py : 166] :: Checked Out Connections from Pool  0
2023-08-23 15:58:46 - INFO - [create_app.py : 167] :: Checked in Connections available in Pool :: 0
2023-08-23 15:58:46 - INFO - [create_app.py : 168] :: Current Pool Overflow Info :: -100
2023-08-23 15:58:46 - INFO - [create_app.py : 169] :: #---------------------------------[ POOL - INFO ]----------------------------------------#
