2023-08-21 12:56:41 - INFO - [base_logger.py : 34] :: Initialized logger for the service [authtoken] :: [SUCCESS]
2023-08-21 12:56:41 - INFO - [create_app.py : 42] :: Received Service [authtoken]
2023-08-21 12:56:41 - INFO - [create_app.py : 44] :: Flask of Application Instance created for service [authtoken] ,  App Name :: [<Flask 'authtoken'>] ==> SUCCESS
2023-08-21 12:56:41 - INFO - [create_app.py : 53] :: Created Blueprint :: <Blueprint 'authtoken_bp'> for the Application service ::authtoken
2023-08-21 12:56:41 - INFO - [create_app.py : 71] :: Added Blueprints :: /static/<path:filename>
2023-08-21 12:56:41 - INFO - [create_app.py : 61] :: Registering Error Handler 500-<function internal_server_error at 0x1083b8940> to the service :: <Flask 'authtoken'>
2023-08-21 12:56:41 - INFO - [create_app.py : 61] :: Registering Error Handler 400-<function bad_request at 0x1083b88b0> to the service :: <Flask 'authtoken'>
2023-08-21 12:56:41 - INFO - [create_app.py : 61] :: Registering Error Handler 404-<function not_found at 0x1083b8dc0> to the service :: <Flask 'authtoken'>
2023-08-21 12:56:41 - INFO - [create_app.py : 67] :: Error Code: None, Handler Function: {}
2023-08-21 12:56:41 - INFO - [create_app.py : 81] :: Creating DB-Engine using DatabaseURI for Service :: [authtoken]
2023-08-21 12:56:41 - INFO - [create_app.py : 75] :: Preparing DatabaseURI for Service :: [authtoken]
2023-08-21 12:56:41 - INFO - [create_app.py : 77] :: Prepared DatabaseURI for Service :: [authtoken] - mysql+pymysql://root:Ishi#06041995@127.0.0.1:3305/AUTHTOKENS
2023-08-21 12:56:41 - INFO - [create_app.py : 83] :: Created DB-Engine using DatabaseURIfor Service :: [Engine(mysql+pymysql://root:***@127.0.0.1:3305/AUTHTOKENS)]
2023-08-21 12:56:41 - INFO - [create_app.py : 112] :: Current Connection status set to :: False for the service :: authtoken
2023-08-21 12:56:41 - INFO - [create_app.py : 113] :: Trying to establish the connection to the database :: [IN-PROGRESS]
2023-08-21 12:56:41 - INFO - [create_app.py : 117] :: Established the connection to the database :: [SUCCESS]
2023-08-21 12:56:41 - INFO - [create_app.py : 119] :: Current Connection status set to :: True for the service :: authtoken
2023-08-21 12:56:41 - INFO - [create_app.py : 121] :: Closing the Current Connection as the connection was established for the service :: authtoken
2023-08-21 12:56:41 - INFO - [create_app.py : 154] :: Database already exists :: AUTHTOKENS
2023-08-21 12:56:41 - INFO - [create_app.py : 130] :: Trying to create the tables if not present in the database...
2023-08-21 12:56:41 - INFO - [create_app.py : 132] :: Going to create the tables ...
2023-08-21 12:56:41 - INFO - [create_app.py : 135] :: Created the tables ...
2023-08-21 12:56:41 - INFO - [create_app.py : 88] :: Binding SQLALCHEMY using DatabaseURI:: [mysql+pymysql://root:Ishi#06041995@127.0.0.1:3305/AUTHTOKENS] to Application Instance for Service :: [authtoken]
2023-08-21 12:56:41 - INFO - [create_app.py : 90] :: Binded SQLALCHEMY :: [<SQLAlchemy>] to Application Instance for Service :: [authtoken]
2023-08-21 12:56:41 - INFO - [create_app.py : 94] :: Initialized Pool for Service ==>[authtoken] :: [SUCCESS]
2023-08-21 12:56:41 - INFO - [create_app.py : 163] :: #---------------------------------[ POOL - INFO ]----------------------------------------#
2023-08-21 12:56:41 - INFO - [create_app.py : 164] :: Displaying Pool_Info for Service ==>[authtoken] 
2023-08-21 12:56:41 - INFO - [create_app.py : 165] :: Current Pool Info :: <sqlalchemy.pool.impl.QueuePool object at 0x1084c1730> - ID: 4434171696
2023-08-21 12:56:41 - INFO - [create_app.py : 166] :: Current Pool Size ::  100
2023-08-21 12:56:41 - INFO - [create_app.py : 167] :: Checked Out Connections from Pool  0
2023-08-21 12:56:41 - INFO - [create_app.py : 168] :: Checked in Connections available in Pool :: 0
2023-08-21 12:56:41 - INFO - [create_app.py : 169] :: Current Pool Overflow Info :: -100
2023-08-21 12:56:41 - INFO - [create_app.py : 170] :: #---------------------------------[ POOL - INFO ]----------------------------------------#
2023-08-21 12:56:41 - INFO - [create_app.py : 57] :: Registering blueprints to the service :: <Flask 'authtoken'>
2023-08-21 12:56:41 - INFO - [create_app.py : 71] :: Added Blueprints :: /static/<path:filename>
2023-08-21 12:56:41 - INFO - [create_app.py : 71] :: Added Blueprints :: /api/v1/airliner/generateToken
2023-08-21 12:56:41 - INFO - [token_app.py : 10] :: Started the AUTHTOKENS server ...
2023-08-21 12:56:41 - INFO - [token_app.py : 11] :: Application is ready to server traffic.
